### ISSUE TITLE
Source compile issues

### ISSUE THREAD

**Issue by alanw9876** [CliffHan/R8500-V1.0.2.116_1.0.90#1]
I seem to be having a terrible time getting past all the issues and dependencies in compiling the NetGear code into a final image file.  Did this base of code compile to completion for you and generate a flashable image file?  And did it work if so?
Thanks for any insight!

**Comment by CliffHan** [comment]
Well,  it can be built with the image generated on ubuntu 16.04, but I was not sure if it works because I haven't flashed it for some reason.
